dist: trusty
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox --disable-dev-shm-usage http://localhost &
install:
  - yarn
branches:
  only:
    - master
cache: yarn
language: node_js
node_js:
  - '11.15.0'
notifications:
  email: false
sudo: required
