dist: trusty
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --version
  - ./node_modules/.bin/chromedriver --version
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox --disable-dev-shm-usage http://localhost &
branches:
  only:
    - master
cache: yarn
language: node_js
node_js:
  - '8'
notifications:
  email: false
sudo: required
