publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "guidelines"
    label: "Guidelines"
    folder: "packages/design-system-docs/src/pages/guidelines"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # From example site, this is how we can configure individual pages that have uique structures
  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/index.md"
  #       label: "Landing Page"
  #       name: "index"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "index-page",
  #           }
  #         - { label: Title, name: title, widget: string }
  #         - { label: Image, name: image, widget: image }
  #         - { label: Heading, name: heading, widget: string }
  #         - { label: Subheading, name: subheading, widget: string }
  #         - {
  #             label: Mainpitch,
  #             name: mainpitch,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Title, name: title, widget: string },
  #                 { label: Description, name: description, widget: text },
  #               ],
  #           }
  #         - { label: Description, name: description, widget: string }
  #         - {
  #             label: Intro,
  #             name: intro,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Blurbs,
  #                   name: blurbs,
  #                   widget: list,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Text, name: text, widget: text },
  #                     ],
  #                 },
  #               ],
  #           }
  #         - {
  #             label: Main,
  #             name: main,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Image1,
  #                   name: image1,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image2,
  #                   name: image2,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image3,
  #                   name: image3,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #               ],
  #           }
  #     - file: "src/pages/about/index.md"
  #       label: "About"
  #       name: "about"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "about-page",
  #           }
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
